### PR TITLE
Jk2375/get status

### PR DESCRIPTION
**Pull request by justinkang01**
### Summary 

Created a frontend function to obtain the status of a club based on its open and close dates. 

### Test Plan 
Thought out the logic of the open date and close date.
There are four cases that we need to consider (based on the status):
(define today to be the day that the user is accessing the application)
- open: if a club has a start date, but either: has no end date, or today is within the bounds of the start and end date, we mark the club as open.
- closed: if today is before the start date or after the end date, mark the club as closed
- approaching: if a club has both a start and end date, and the start date is within a week of the day that a user is accessing the app, then we mark this club as approaching
- always open: if a club has not defined BOTH a start and end date, then it can be labelled as always open

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

### CODE REVIEW

**Review by aaronkang7 — DISMISSED** [review]
LGTM!

**Review by aaronkang7 — DISMISSED** [review]

**Comment by altheabata** [comment]
Great job outlining the 4 states for the logic!

**Review by altheabata — COMMENTED** [review]
Great implementation of the new 4 logic states

**Review by JustKong13 — APPROVED** [review]
Like the change from status: string to status: StatusType. Although it's nice to have, I'm not sure we have to return data (on line 7). Other than that everything looks good to me other than just the merge conflict

**Pull request merged**
