### PR TITLE
hw424/style-searchbar

### PR DESCRIPTION
**Pull request by 20austinw**
### Summary 

This pull request is the first step towards styling the NavBar. The font is still mismatched, which would be fixed after the global fonts are set in the CSS file. 

- [x] Styled the search bar

### Test Plan 
image

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

### CODE REVIEW

**Review by aaronkang7 — COMMENTED** [review]
Great work with the search bar! But I've realized that other links on the Navbar are now off-center. Would be great if you could take care of that!

**Comment by 20austinw** [comment]
Not sure if this is what you mean by centered, but I fixed some of the positionings.

**Review by aaronkang7 — COMMENTED** [review]
Sorry, Austin! I meant vertically aligned. I realized the Profile and Register button was stuck on top rather than vertically centered. The initial horizontal alignment was okay. :)

**Comment by rgu0114** [comment]
Looks pretty good! The styling looks really nice. Just curious though, why did you change the .left css class from display inline-block? What makes that class different instead of the other classes that mostly have inline-block?

**Review by aaronkang7 — APPROVED** [review]
LGTM!

**Pull request merged**
